# Generated by Django 4.2.4 on 2023-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_article_user_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
